### ISSUE TITLE
Expose expressions API

### ISSUE THREAD

**Issue by kevinheavey** [pola-rs/pyo3-polars#1]
This crate exposes `Series` and `DataFrame`, but sometimes people write a bunch of functions that return `Expr`s (e.g. [tidypolars](https://github.com/markfairbanks/tidypolars)).

 It would be nice to be able to write these kinds of functions once in Rust and reuse them in Python.

Not sure if [my favourite PyO3 issue](https://github.com/PyO3/pyo3/issues/1444) makes this impossible for now

**Comment by ritchie46** [comment]
We can use serde json to serializw/deserialize expressions. I can add this as well .

**Comment by grantslatton** [comment]
would this also make it so `LazyFrame` could bi `IntoPy`/`FromPyObj`? that would be very useful

**Comment by aldanor** [comment]
Can be closed now that there's an experimental version of the expressions API released?

**Comment by ritchie46** [comment]
Yes, it is not exactly what was asked. But I think the derive expressions is the way to go.
