### ISSUE TITLE
libc::write argument type error

### ISSUE THREAD

**Issue by Eizm** [pola-rs/pyo3-polars#101]
When I try to build this as a dependency (cargo new asdf, then adding pyo3-polars = "0.16" to dependencies, then running cargo build) I get a compile error in a libc::write call due to an argument type:

```
...
Compiling polars-parquet v0.42.0
Compiling pyo3-polars v0.16.1
error[E0308]: mismatched types
   --> C:\Users\eizinger\.cargo\registry\src\index.crates.io-6f17d22bba15001f\pyo3-polars-0.16.1\src\alloc.rs:83:78
    |
83  |                 unsafe { libc::write(2, msg.as_ptr() as *const libc::c_void, msg.len()) };
    |                          -----------                                         ^^^^^^^^^ expected `u32`, found `usize`
    |                          |
    |                          arguments to this function are incorrect
    |
```

 I don't really understand it, because when I look up the docs on libc::write, it clearly says that it expects size_t. So maybe something is wrong on my system?

Running on Windows. Toolchain and libc versions below:

```
D:\SW_playground\py03_polars_test>rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\eizinger\.rustup

installed targets for active toolchain
--------------------------------------

i686-pc-windows-msvc
wasm32-unknown-unknown
x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
```

```
D:\SW_playground\py03_polars_test>cargo tree | grep libc
    ├── libc v0.2.156
    │   │   │       ├── libc v0.2.156
    │   ├── libc v0.2.156
    │   │   └── libc v0.2.156
```

I'm not exactly an expert on everything related to compilation, so it's probably something silly because otherwise someone else would've encountered this.
Any help would be appreciated; sorry if this is not the right venue, I don't really know where else to ask.

**Comment by broadhed** [comment]
I have the same problem on Windows, tried falling back to a lower version and couldn't get that to work either.

**Comment by broadhed** [comment]
I ended up just vendoring `pyo3-polars` and making the changes the compiler suggested.

1. Make a `vendor` dir
2. Clone the package into it:

`C:\Users\broadhed\plugin_project\vendor> git clone git@github.com:pola-rs/pyo3-polars.git

3. Adjust Cargo.toml to go to the `vendor` directory instead of internet for this package
```toml
# in Cargo.toml

# pyo3-polars is vendored, see below
# pyo3-polars = { version = "0.16.0", features = ["derive"] }
pyo3-polars = { path = "vendor/pyo3-polars/pyo3-polars", features= ["derive"] }
```
You can run `rustc metadata` at this point. If no errors, everything is working fine.

4. Make the rustc recommended changes to `plugin_project\vendor\pyo3-polars\pyo3-polars\src\alloc.rs` line 80:
```diff
-                unsafe { libc::write(2, msg.as_ptr() as *const libc::c_void, msg.len()) };
+                unsafe { libc::write(2, msg.as_ptr() as *const libc::c_void, msg.len().try_into().unwrap()) };
```

5. Now you should be able to rustc/maturin your project with no compile errors

**Comment by Eizm** [comment]
I see, that'll work, thanks for the detailed instructions!

**Comment by langslike** [comment]
I have this same error, the description is here: https://github.com/MarcoGorelli/polars-plugins-tutorial/issues/45

**Comment by jetuk** [comment]
> I don't really understand it, because when I look up the docs on libc::write, it clearly says that it expects size_t. So maybe something is wrong on my system?

On Windows the type is `c_unit` which is an alias for `u32`. So, it's not a problem with your setup but with the signature of `libc::write` being different between the platforms.
