### ISSUE TITLE
No module named 'polars.utils'

### ISSUE THREAD

**Issue by david-waterworth** [pola-rs/pyo3-polars#110]
The code from the examples

```
from polars.utils.udfs import _get_shared_lib_location
```

fails with 

```
No module named 'polars.utils'
```

It looks like `_get_shared_lib_location` needs to be replaced with `register_plugin_function` but the readme still refers to `_get_shared_lib_location`

**Comment by MarcoGorelli** [comment]
thanks @david-waterworth for reporting, indeed it's quite outdated
