### ISSUE TITLE
Cannot create polars series from UInt16 type

### ISSUE THREAD

**Issue by astralcai** [pola-rs/pyo3-polars#3]
It seems that `u16` is not supported. I tried to create a data frame where the `dtype` of my columns are set to `u16`, and when I try to pass this data frame to my rust program, I get

```Cannot create polars series from UInt16 type```

**Comment by ritchie46** [comment]
Have you activated all features?

**Comment by astralcai** [comment]
> Have you activated all features?

How do I do that?

**Comment by ritchie46** [comment]
https://doc.rust-lang.org/cargo/reference/features.html
