### ISSUE TITLE
New polars version broke this wrapper

### ISSUE THREAD

**Issue by SimonG85** [pola-rs/pyo3-polars#5]
With the release 0.27 of polars this crate has been broken.

In particular, the function into() that allows to transform a PyDataFrame into a polars DataFrame is broken.

The compiler says:
"the trait bound `polars::prelude::DataFrame: From<PyDataFrame>` is not satisfied
the trait `From<&polars::prelude::Schema>` is implemented for `polars::prelude::DataFrame`
required for `PyDataFrame` to implement `Into<polars::prelude::DataFrame>`"

With 0.26 version of polars it works perfectly.

I have checked and also the example is broken.

**Comment by ritchie46** [comment]
Right. We need to update the polars dependency.

**Comment by SimonG85** [comment]
Can I help you? I tried to compile by myself but I found several problems in many places.

**Comment by ritchie46** [comment]
Yes, the cargo.toml needs to be updated.

**Comment by ritchie46** [comment]
Published.
