### ISSUE TITLE
How to pass kwarg to func output type

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/pyo3-polars#58]
We added a function in polars-xdt which changes the timezone of the datetime, this know at hand since we pass the time-zone through the kwargs, see some example code here to mimic the behaviour:

```rust
#[derive(Deserialize)]
pub struct OutputKwargs{
    to_tz: std::string::String,
}

pub fn output(input_fields: &[Field]) -> PolarsResult<Field> {
    let field = input_fields[0].clone();
    let dtype = match field.dtype {
        DataType::Datetime(unit, _) => DataType::Datetime(unit, "SET TZ HERE from KWARGS"),
        _ => polars_bail!(InvalidOperation:
            "dtype '{}' not supported", field.dtype
        ),
    };
    Ok(Field::new(&field.name, dtype))
}
#[polars_expr(output_type_func=output)]
fn function(inputs: &[Series], kwargs: OutputKwargs) -> PolarsResult<Series> {
    let s1 = &inputs[0];
    let ca = s1.datetime().unwrap();
    let converted = ca.clone().convert_time_zone(kwargs.to_tz)?;
    
    Ok(converted.clone().into_series())
}

```

I would like to pass the kargs.to_tz to the from_local_datetime_output, is this possible? If not how should I handle the func output type in that case.

Do you have any ideas @ritchie46?

**Comment by ritchie46** [comment]
You will have to compile to expressions. In your `register_plugin` you will then know which expression to call.

**Comment by ion-elgreco** [comment]
@ritchie46 so I would have to create an expression with a func_output_field for each timezone?

**Comment by ritchie46** [comment]
Oh.. it is different for every timezone? Hmm.. have to think about this.

**Comment by ion-elgreco** [comment]
Yes, the user provided the timezone, and then the function returns the datetime with this timezone
