### ISSUE TITLE
Allow for custom datasources as plugins

### ISSUE THREAD

**Issue by universalmind303** [pola-rs/pyo3-polars#74]
The current system makes it pretty easy to add new transformations (expr)'s as plugins, but there is currently no good way for users to provide custom datasources. 

---

Ideally, custom datasources should be as easy as implementing a trait or macro. There is already the `AnonymousScan` trait that mostly works for this use case, but doesn't work via pyo3-polars due to (de)serialization issues (see https://github.com/pola-rs/pyo3-polars/issues/67). Maybe we can have an FFI equivalent instead of the in memory `AnonymousScan`? 

If we loosely base it off of datafusion's [TableProvider](https://docs.rs/datafusion/latest/datafusion/datasource/provider/trait.TableProvider.html) it may look something like this

```rs
pub struct DummyDatasource {}

impl PolarsDatasource for DummyDatasource {
  fn schema(&self) -> SchemaRef {
    Arc::new(Schema::empty())
  }
  fn scan(&self, projection: &Option<Vec<usize>>, filters: &[Expr], limit: Option<usize>) -> Result<Box<dyn Executor>> {
    Ok(Box::new(DummyExec::new()))}
  }
}

pub struct DummyExec {}

impl DummyExec {
    pub fn new() -> Self {
        DummyExec {}
    }
}

impl Executor for DummyExec {
    fn execute(&mut self, cache: &mut ExecutionState) -> PolarsResult<DataFrame> {
        Ok(DataFrame::empty())
    };
}

```

## Related issues

https://github.com/pola-rs/pyo3-polars/issues/67

**Comment by NielsPraet** [comment]
For my thesis I am currently looking at how I can hook an existing backend query service into Polars to use the Lazy DataFrame API. This however would need to be passed from the Rust side to the Python side as the use-case is aimed at Data Scientists / ML Engineers working in Python. From what I gathered it unfortunately seems to be impossible to do so right now, so I want to +1 this issue as this would in general open up a lot of possibilities for the Polars eco system!

**Comment by shahamran** [comment]
Can anyone suggest how to work around this limitation? That is, how can I "extend polars" to support scanning my custom file formats?

I looked at https://github.com/universalmind303/polars-mongo which seems clean and straight-forward, but suffers from the same limitation as in #67.

**Comment by hantusk** [comment]
You might be able to scan your custom file formats using [fsspec](https://filesystem-spec.readthedocs.io/en/latest/). Here's an example: [https://csvbase.com/blog/7](https://csvbase.com/blog/7).

**Comment by shahamran** [comment]
@hantusk this looks very cool and potentially a good workaround. Thanks for sharing!

**Comment by ritchie46** [comment]
This is something I want to get into to.

**Comment by shahamran** [comment]
Hi @ritchie46, I've been using the newly released IO plugins and it works well, thank you.

I have a question regarding `n_rows`. In the [docstring] it says:

> n_rows: Materialize only n rows from the source. The reader can stop when `n_rows` are read.

Is it before or after the predicate is applied? In this context, what's the meaning of "materialize"?

Thanks again for implementing this!

[docstring]: <https://github.com/pola-rs/polars/blob/py-1.4.1/py-polars/polars/io/plugins.py#L38>

**Comment by ritchie46** [comment]
Here is the working example; https://github.com/pola-rs/pyo3-polars/tree/main/example/io_plugin

**Comment by shahamran** [comment]
@ritchie46 thank you.

I understand from this that `n_rows` can be used regardless of predicate. I have another question. Can I modify n_rows to account for batch sizes? e.g.:

```py
def _read_my_format_impl(path: str, ...) -> pl.DataFrame: ...

def scan_my_format(paths, ...) -> pl.LazyFrame:
    def _read_my_format(with_columns, predicate, n_rows, batch_size):
        for path in paths:
            df = _read_my_format_impl(path, columns=with_columns, n_rows=n_rows)
            if predicate is not None:
                df = df.filter(predicate)
            yield df
            if n_rows is not None:
                n_rows -= df.height  # <-- is this legit?
                if n_rows <= 0:
                    break

    return register_io_source(callable=_read_my_format, schema=...)
```

**Comment by ritchie46** [comment]
Maybe. You are not allowed to return more than `n_rows`. It is the upper limit.
